# Generated by Django 5.1.2 on 2024-10-25 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('liga', models.CharField(choices=[('Primera A', 'Primera división'), ('Primera B', 'Segunda división'), ('Sin división', 'club sin divisón')], default='Sin división', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dorsal', models.PositiveSmallIntegerField(max_length=3)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MC', 'Medio campo'), ('DEL', 'Delantero'), ('SP', 'Sin posición')], default='SP', max_length=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='club.club')),
            ],
        ),
    ]
