# Generated by Django 5.1.2 on 2024-10-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
