# Generated by Django 5.1.2 on 2024-10-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_imagen_alter_club_liga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': [('can_edit_clubes', 'Puede editar clubes')]},
        ),
    ]
